from processing.bugprocessor import process as process_bug
import argparse


def main(args):
    """
    Main CLI entry point for BUGZAP.
    """
    if args.json and args.name:
        process(args.json, args.name)
    elif args.retrieve and args.name:
        retrieve(args.retrieve, args.name)
    else:
        print "Nothing to do."


def process(bugs_file, bugs_data_name):
    """
    Given a source file containing bugzilla reports in json format, produce keyword n-grams extracted
    from the report bodies.
    """
    path = 'bugzap/bugzap/visualization/data/' + bugs_data_name + '/'
    process_bug(bugs_file, path)


def retrieve(url_file, bugs_data_name):
    """
    Given a txt file containing a starting url bugzilla query and domain name,
    start a spider and retrieve all bug reports pertaining to
    that starting url.
    """
    pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Produce keywords and n-grams extracted from Bugzilla reports.')
    parser.add_argument("-j", "--json", help='A json file containing generated by bug_spider.')
    parser.add_argument("-n", "--name", help='A name for the set of reports generated.')
    parser.add_argument("-r", "--retrieve", help='A plain txt file containing the starting URL and domain for bugzilla'
                                                 'report retreival.')
    args = parser.parse_args()
    main(args)
