import argparse
from BugProcessors.bugzilla_processor import BugzillaProcessor
from BugProcessors.jira_processor import JiraProcessor


def main(args):
    """
    Main CLI entry point for BUGZAP.
    """

    process(args.json, args.name, args.reports, args.blacklist)


def process(bugs_file, bugs_data_name, report_type, black_list):
    """
    Given a source file containing bugzilla reports in json format, produce keyword n-grams extracted
    from the report bodies.
    """
    if 'bugzilla' in report_type:
        BugzillaProcessor(bugs_file, bugs_data_name, black_list)
    else:
        JiraProcessor(bugs_file, bugs_data_name, black_list)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Produce keywords and n-grams extracted from bug reports.')
    parser.add_argument("-j", "--json", required=True,
                        help='A json file containing generated by a bug_spider.')
    parser.add_argument("-n", "--name", required=True,
                        help='A name for the set of reports generated.')
    parser.add_argument("-r", "--reports", choices=['bugzilla', 'jira'], required=True,
                        help='Issue reporting site.')
    parser.add_argument("-b", "--blacklist",
                        help="Path to file containing tokens black list for dataset.")
    args = parser.parse_args()
    main(args)
