import argparse
from bugprocessor import BugProcessor
from keyextractor.src.extractor import Extractor


def main(args):
    """
    Main CLI entry point for BUGZAP.
    """
    if args.json and args.name:
        process(args.json, args.name)
    elif args.retrieve and args.name:
        retrieve(args.retrieve, args.name)
    else:
        print "Nothing to do."


def process(bugs_file, bugs_data_name):
    """
    Given a source file containing bugzilla reports in json format, produce keyword n-grams extracted
    from the report bodies.
    """
    BugProcessor(bugs_file, bugs_data_name)


def retrieve(url, domain, bugs_data_name):
    """
    Given a txt file containing a starting url bugzilla query and domain name,
    start a spider and retrieve all bug reports pertaining to
    that starting url.
    """
    # spider = BugQuerySpider(query=url, domain=domain)
    # settings = get_project_settings()
    # crawler = Crawler(settings)
    # crawler.signals.connect(reactor.stop, signal=signals.spider_closed)
    # crawler.configure()
    # crawler.crawl(spider)
    # crawler.start()
    # log.start()
    # reactor.run()
    pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Produce keywords and n-grams extracted from Bugzilla reports.')
    parser.add_argument("-j", "--json", help='A json file containing generated by bug_spider.')
    parser.add_argument("-n", "--name", help='A name for the set of reports generated.')
    parser.add_argument("-r", "--retrieve", help='A plain txt file containing the starting URL and domain for bugzilla'
                                                 'report retreival.')
    args = parser.parse_args()
    main(args)
